import torch
from torch_geometric.data import Data 

edge_index = torch.tensor([[0, 1],
                        [0, 4],
                        [1, 0],
                           [1, 5],
                           [1, 2],
                           [2, 1],
                           [2, 6],
                           [2, 3],
                           [3, 2],
                           [3, 7],
                           [4, 0],
                           [4, 5],
                           [4, 8],
                           [5, 1],
                           [5, 4],
                           [5, 9],
                           [5, 6],
                           [6, 2],
                           [6, 5],
                           [6, 10],
                           [6, 7],
                           [7, 3],
                           [7, 6],
                           [7, 11],
                           [8, 4],
                           [8, 9],
                           [8, 12],
                           [9, 5],
                           [9, 8],
                           [9, 13],
                           [9, 10],
                           [10, 6],
                           [10, 9],
                           [10, 14],
                           [10, 11],
                           [12, 8],
                           [12, 13],
                           [13, 9],
                           [13, 12],
                           [13, 14],
                           [14, 10],
                           [14, 13],
                           [14, 15],
                           [15, 11],
                           [15, 14]], dtype=torch.long)

x = torch.rand(16, requires_grad=True).unsqueeze(1)

dataset = Data(x=x, edge_index=edge_index.t().contiguous())